bands = [["Funkadelic",          ["George Clinton",
                                  "Grady Thomas",
                                  "Ray Davis",
                                  "Clarence 'Fuzzy' Haskins",
                                  "Calvin Simon",
                                  "Billy Bass Nelson",
                                  "Eddie Hazel",
                                  "Tawl Ross",
                                  "Tiki Fulwood",
                                  "Mickey Atkins",
                                  "Bernie Worrell",
                                  "Harold Beane",
                                  "Garry Shider",
                                  "Cordell 'Boogie' Mosson",
                                  "William 'Bootsy' Collins",
                                  "Phelps 'Catfish' Collins",
                                  "Ron Bykowski",
                                  "Prakash John",
                                  "Tyrone Lampkin",
                                  "Leon Patillo",
                                  "Jimi Calhoun",
                                  "Michael Hampton",
                                  "Glen Goins",
                                  "Jerome 'Bigfoot' Brailey",
                                  "Dawn Silva",
                                  "Walter 'Junie' Morrison",
                                  "Rodney Curtis",
                                  "Mallia Franklin",
                                  "Larry Fratangelo",
                                  "DeWayne 'Blackbyrd' McKnight",
                                  "David Spradley",
                                  "Daniel 'Ribsy' Owens",
                                  "Ruth Copeland",
                                  "Dennis Chambers"]
         ],
         ["Parliarment",         ["George Clinton",
                                  "Ray Davis",
                                  "Clarence 'Fuzzy' Haskins",
                                  "Calvin Simon",
                                  "Grady Thomas",
                                  "Billy Bass Nelson",
                                  "Eddie Hazel",
                                  "Tawl Ross",
                                  "Tiki Fulwood",
                                  "Mickey Atkins",
                                  "Bernie Worrell",
                                  "William 'Bootsy' Collins",
                                  "Cordell Mosson",
                                  "Rodney 'Skeet' Curtis",
                                  "Garry Shider",
                                  "Prakash John",
                                  "Tyrone Lampkin",
                                  "Glenn Goins",
                                  "Michael Hampton",
                                  "Debbie Wright",
                                  "Gary 'Muddbone' Cooper",
                                  "Jerome Brailey",
                                  "Fred Wesley",
                                  "Maceo Parker",
                                  "Michael Brecker",
                                  "Randy Brecker",
                                  "Rick Gardner",
                                  "Reunald 'Renny' Jones",
                                  "Jeanette Washington",
                                  "Mallia Franklin",
                                  "Dawn Silva",
                                  "Lynn Mabry",
                                  "Ron Ford",
                                  "Shirley Hayden",
                                  "Greg Thomas",
                                  "Larry Heckstall",
                                  "Walter 'Junie' Morrison",
                                  "Robert 'P-Nut' Johnson",
                                  "Ruth Copeland"]],
         ["Bootsy's Rubber Band",["William 'Bootsy' Collins",
                                  "Phelps 'Catfish' Collins",
                                  "Robert 'P-Nut' Johnson"]],
         ["The Talking Heads",   ["Bernie Worrell"]],
         ["The J.B.'s'",         ["Maceo Parker",
                                  "William 'Bootsy' Collins",
                                  "Phelps 'Catfish' Collins",]],
         ["Deee-Lite",           ["William 'Bootsy' Collins"]]
]
bands.each do |band, members|
  new_band = Band.create(name: band)
  members.each do |member|
    new_band.members.create(name: member)
  end
end
